In [2]:
import pandas as pd
import numpy as np
import csv


md = pd.read_csv("BIRAFFE-metadata.csv", sep=';')
#usunięcie tych rekordów gdzie osoba nie ma danych z gry w space
md = md[pd.notnull(md['SPACE'])]
md = md[pd.notnull(md['OPENNESS'])]
#zostawienie id tych osób, bo pliki mają w nazwie id
ids = md['ID'].values

In [4]:
import csv
import json    
print("start")
pd.set_option('display.max_columns', 500)
#import metadata
data = pd.read_csv("merged_scores.csv", sep=',')
data = data[pd.notnull(data['OPENNESS'])]
data = data[pd.notnull(data['CONSCIENTIOUSNESS'])]
data = data[pd.notnull(data['EXTRAVERSION'])]
data = data[pd.notnull(data['AGREEABLENESS'])]
data = data[pd.notnull(data['NEUROTICISM'])]

data=data[data.Score == 'GameOver']
#data.head(25)
type(data)
mean_c=[]

with open('mean_scores.csv', 'w', newline='') as csvfile:
    #nazwy kolumn- wszystkie z plików json
    fieldnames = ["P_ID","OPENNESS","CONSCIENTIOUSNESS","EXTRAVERSION","AGREEABLENESS","NEUROTICISM","RESULT"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    #ustawienie nagłówków
    writer.writeheader()
    for my_id in ids:
        data1=data.loc[data['P_ID'] == my_id]
        nr=data1.shape[0]
        #print(data1)
        score=data1['Value'].sum()
        if (score):
            mean = score/nr
            #print(mean)
            new_data={ 'P_ID': data1['P_ID'].iloc[0], 'OPENNESS': data1['OPENNESS'].iloc[0], 'CONSCIENTIOUSNESS': data1['CONSCIENTIOUSNESS'].iloc[0],'EXTRAVERSION':  data1['EXTRAVERSION'].iloc[0],'AGREEABLENESS': data1['AGREEABLENESS'].iloc[0],'NEUROTICISM': data1['NEUROTICISM'].iloc[0],'RESULT': mean}
            writer.writerow(new_data)

start

In [8]:
data = pd.read_csv("mean_scores.csv", sep=',')

def mapping(x, labels, data, width):
        for i in range(len(labels)):
            if x <= data.quantile((i + 1) * width):
                return labels[i]

def divide_into(labels, data):    
    return data.map(lambda x: mapping(x, labels, data, 1/len(labels)))

data['OPENNESS_CLASS'] = divide_into(['low', 'medium', 'high'], data['OPENNESS'])
data['CONSCIENTIOUSNESS_CLASS'] = divide_into(['low', 'medium', 'high'], data['CONSCIENTIOUSNESS'])
data['AGREEABLENESS_CLASS'] = divide_into(['low', 'medium', 'high'], data['AGREEABLENESS'])
data['RESULT_CLASS'] = divide_into(['low', 'medium', 'high'], data['RESULT'])

data.head()

,P_ID,OPENNESS,CONSCIENTIOUSNESS,EXTRAVERSION,AGREEABLENESS,NEUROTICISM,RESULT,OPENNESS_CLASS,CONSCIENTIOUSNESS_CLASS,AGREEABLENESS_CLASS,RESULT_CLASS
0,1107,4.0,6.0,10.0,4.0,3.0,1526.666667,low,medium,low,high
1,1153,5.0,3.0,8.0,3.0,8.0,262.142857,medium,low,low,low
2,1233,6.0,8.0,7.0,10.0,2.0,792.000000,medium,high,high,medium
3,1318,3.0,6.0,5.0,5.0,2.0,140.000000,low,medium,low,low
4,1400,4.0,6.0,5.0,6.0,6.0,95.000000,low,medium,medium,low